language: node_js
node_js:
- node
cache:
- npm
services:
- docker
script:
- export IMAGE_TAG=$DOCKER_USERNAME/`node -p "require('./package.json').name"`:`node -p "require('./package.json').version"`
- npm run e2e:ci
- npm run test:ci
- npm run lint
- docker build -t $IMAGE_TAG .
before_deploy:
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
deploy:
  provider: script
  script: docker push $IMAGE_TAG
  on:
    branch: master